name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Build
      run: |
        cargo build --verbose
        mkdir output
        cp target/debug/tekst output/tekst
    
    - name: Release
      uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: continuous
          name: Continuous build
          prerelease: True
          artifacts: "output/*"
          token: ${{ secrets.GITHUB_TOKEN }}