name: Release Binary

# Run this after building
on:
  workflow_run:
    workflows: ["Build Binary"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: continuous
          name: Continuous build
          prerelease: True
          artifacts: "target/debug/tekst"
          token: ${{ secrets.GITHUB_TOKEN }}